//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int PenId { get; set; }
        public int CustomerId { get; set; }
        public int Count { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Pen Pen { get; set; }
    }
}
